import type { GitHubService } from "../modules/portal/services/github.js";
import type { ReviewerAgent } from "../services/agent/reviewer-agent.js";
import type { SSEManager } from "./sse-manager.js";
import type {
  AgentPrStatus,
  PrPipelineConfig,
  AgentExecutionResult,
  PrReviewResult,
} from "@foundry-x/shared";

export interface AgentPrResult {
  id: string;
  prNumber: number | null;
  prUrl: string | null;
  branch: string;
  status: AgentPrStatus;
  reviewResult?: PrReviewResult;
  merged: boolean;
}

const DEFAULT_CONFIG: PrPipelineConfig = {
  autoMerge: true,
  requireHumanApproval: false,
  maxAutoMergePerDay: 10,
  branchPrefix: "agent/",
  mergeStrategy: "squash",
  sddScoreThreshold: 80,
  qualityScoreThreshold: 70,
};

function toSnakeCase(str: string): string {
  return str.replace(/([A-Z])/g, "_$1").toLowerCase().replace(/^_/, "");
}

export class PrPipelineService {
  private config: PrPipelineConfig;

  constructor(
    private github: GitHubService,
    private reviewer: ReviewerAgent,
    private db: D1Database,
    private sse?: SSEManager,
    config?: Partial<PrPipelineConfig>,
  ) {
    this.config = { ...DEFAULT_CONFIG, ...config };
  }

  async createAgentPr(
    agentId: string,
    taskId: string,
    taskResult: AgentExecutionResult,
  ): Promise<AgentPrResult> {
    const files = taskResult.output.generatedCode;
    if (!files?.length) {
      throw new Error("No generated code to create PR from");
    }

    const branch = `${this.config.branchPrefix}${taskId}`;

    // 1. Create DB record
    const prRecordId = await this.createPrRecord(agentId, taskId, branch);

    // 2. Create branch
    await this.github.createBranch(branch);

    // 3. Commit files
    const commitMessage = `feat(agent): ${agentId} — task ${taskId}\n\nAuto-generated by Foundry-X agent pipeline`;
    const commit = await this.github.createCommitWithFiles(
      branch,
      files.map((f) => ({ path: f.path, content: f.content, action: f.action })),
      commitMessage,
    );

    // 4. Create PR
    const prBody = this.buildPrBody(agentId, taskId, taskResult);
    const pr = await this.github.createPullRequest({
      title: `[Agent] ${agentId}: ${taskId}`,
      body: prBody,
      head: branch,
      base: "master",
      labels: ["agent-pr", "auto-generated"],
    });

    // 5. Update record with PR info
    await this.updatePrRecord(prRecordId, {
      status: "open",
      prNumber: pr.number,
      prUrl: pr.htmlUrl,
    });

    // SSE: pr.created
    this.sse?.pushEvent({
      event: "agent.pr.created",
      data: { prNumber: pr.number, branch, agentId, taskId },
    });

    // 6. Review the PR
    const diff = await this.github.getPrDiff(pr.number);
    const reviewResult = await this.reviewer.reviewPullRequest(diff, {
      agentId,
      taskId,
      taskType: "code-generation",
      prNumber: pr.number,
    });

    // 7. Post review to GitHub
    const ghEvent = reviewResult.decision === "approve"
      ? "APPROVE" as const
      : reviewResult.decision === "request_changes"
        ? "REQUEST_CHANGES" as const
        : "COMMENT" as const;

    await this.github.createPrReview(pr.number, {
      body: reviewResult.summary,
      event: ghEvent,
    });

    await this.updatePrRecord(prRecordId, {
      status: "reviewing",
      reviewAgentId: "reviewer-agent",
      reviewDecision: reviewResult.decision,
      sddScore: reviewResult.sddScore,
      qualityScore: reviewResult.qualityScore,
      securityIssues: JSON.stringify(reviewResult.securityIssues),
    });

    // SSE: pr.reviewed
    this.sse?.pushEvent({
      event: "agent.pr.reviewed",
      data: {
        prNumber: pr.number,
        decision: reviewResult.decision,
        sddScore: reviewResult.sddScore,
        reviewerAgentId: "reviewer-agent",
      },
    });

    // 8. Check and merge
    const mergeResult = await this.checkAndMerge(prRecordId, pr.number, reviewResult);

    return {
      id: prRecordId,
      prNumber: pr.number,
      prUrl: pr.htmlUrl,
      branch,
      status: mergeResult.merged ? "merged" : mergeResult.needsHuman ? "needs_human" : "approved",
      reviewResult,
      merged: mergeResult.merged,
    };
  }

  async checkAndMerge(
    prRecordId: string,
    prNumber: number,
    reviewResult: PrReviewResult,
  ): Promise<{ merged: boolean; needsHuman: boolean; reason?: string }> {
    const blockers: string[] = [];

    // Gate 1: Review approved
    if (reviewResult.decision !== "approve") {
      blockers.push(`Review decision: ${reviewResult.decision}`);
    }

    // Gate 2: SDD score threshold
    if (reviewResult.sddScore < this.config.sddScoreThreshold) {
      blockers.push(`SDD score ${reviewResult.sddScore} < ${this.config.sddScoreThreshold}`);
    }

    // Gate 3: Quality score threshold
    if (reviewResult.qualityScore < this.config.qualityScoreThreshold) {
      blockers.push(`Quality score ${reviewResult.qualityScore} < ${this.config.qualityScoreThreshold}`);
    }

    // Gate 4: No critical security issues
    if (reviewResult.securityIssues.length > 0) {
      blockers.push(`Security issues: ${reviewResult.securityIssues.length}`);
    }

    // Gate 5: CI green (check runs)
    try {
      const checks = await this.github.getCheckRuns(`pull/${prNumber}/head`);
      if (checks.conclusion !== "success" && checks.total > 0) {
        blockers.push(`CI status: ${checks.conclusion ?? "pending"}`);
      }
    } catch {
      // No check runs configured — skip gate
    }

    // Gate 6: Daily limit
    const todayCount = await this.getTodayMergeCount();
    if (todayCount >= this.config.maxAutoMergePerDay) {
      blockers.push(`Daily auto-merge limit reached (${todayCount}/${this.config.maxAutoMergePerDay})`);
    }

    // Gate 7: Human approval
    if (this.config.requireHumanApproval) {
      blockers.push("Human approval required");
    }

    // Auto-merge disabled
    if (!this.config.autoMerge) {
      blockers.push("Auto-merge disabled");
    }

    if (blockers.length > 0) {
      await this.updatePrRecord(prRecordId, { status: "needs_human" });

      this.sse?.pushEvent({
        event: "agent.pr.review_needed",
        data: {
          prNumber,
          reason: blockers[0]!,
          blockers,
        },
      });

      return { merged: false, needsHuman: true, reason: blockers.join("; ") };
    }

    // All gates passed — merge
    const mergeResult = await this.github.mergePullRequest(prNumber, {
      mergeMethod: this.config.mergeStrategy,
    });

    const branch = await this.getBranchFromRecord(prRecordId);
    if (branch) {
      await this.github.deleteBranch(branch);
    }

    await this.updatePrRecord(prRecordId, {
      status: "merged",
      mergedAt: new Date().toISOString(),
      commitSha: mergeResult.sha,
    });

    this.sse?.pushEvent({
      event: "agent.pr.merged",
      data: {
        prNumber,
        mergedAt: new Date().toISOString(),
        commitSha: mergeResult.sha,
      },
    });

    return { merged: true, needsHuman: false };
  }

  // ─── Private Helpers ───

  private async createPrRecord(agentId: string, taskId: string, branch: string): Promise<string> {
    const id = `pr-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
    await this.db
      .prepare(
        `INSERT INTO agent_prs (id, agent_id, task_id, repo, branch, status, merge_strategy)
         VALUES (?, ?, ?, ?, ?, 'creating', ?)`,
      )
      .bind(id, agentId, taskId, "KTDS-AXBD/Foundry-X", branch, this.config.mergeStrategy)
      .run();
    return id;
  }

  private async updatePrRecord(
    id: string,
    fields: Record<string, string | number | null>,
  ): Promise<void> {
    const entries = Object.entries(fields);
    const setClauses = entries.map(([k]) => `${toSnakeCase(k)} = ?`).join(", ");
    const values = entries.map(([, v]) => v);

    await this.db
      .prepare(`UPDATE agent_prs SET ${setClauses}, updated_at = datetime('now') WHERE id = ?`)
      .bind(...values, id)
      .run();
  }

  private async getTodayMergeCount(): Promise<number> {
    const result = await this.db
      .prepare(
        `SELECT COUNT(*) as count FROM agent_prs
         WHERE status = 'merged' AND merged_at >= date('now')`,
      )
      .first<{ count: number }>();
    return result?.count ?? 0;
  }

  private async getBranchFromRecord(id: string): Promise<string | null> {
    const result = await this.db
      .prepare("SELECT branch FROM agent_prs WHERE id = ?")
      .bind(id)
      .first<{ branch: string }>();
    return result?.branch ?? null;
  }

  private buildPrBody(
    agentId: string,
    taskId: string,
    taskResult: AgentExecutionResult,
  ): string {
    const files = taskResult.output.generatedCode ?? [];
    const fileList = files.map((f) => `- \`${f.path}\` (${f.action})`).join("\n");

    return `## Agent-Generated Pull Request

**Agent:** ${agentId}
**Task:** ${taskId}
**Status:** ${taskResult.status}
**Model:** ${taskResult.model}
**Tokens Used:** ${taskResult.tokensUsed}

### Changed Files
${fileList}

### Analysis
${taskResult.output.analysis ?? "No analysis provided."}

---
_Generated by Foundry-X Agent Pipeline_`;
  }
}
