import type { HarnessBuilder } from './types.js';

/** project-context.md 생성 빌더 — RepoProfile 기반 프로젝트 맥락 문서 */
export const buildProjectContext: HarnessBuilder = (profile) => {
  const sections: string[] = [];

  sections.push('# Project Context');
  sections.push('');
  sections.push('> Auto-generated by `foundry-x init` — edit freely, merges preserved on re-init.');
  sections.push('');

  // Summary
  sections.push('## Summary');
  sections.push('');
  sections.push(profile.projectContext?.summary ?? 'No README found');
  sections.push('');

  // Tech Stack
  sections.push('## Tech Stack');
  sections.push('');
  sections.push(`- **Languages**: ${profile.languages.join(', ') || '(none detected)'}`);
  sections.push(`- **Frameworks**: ${profile.frameworks.join(', ') || '(none detected)'}`);
  sections.push(`- **Build Tools**: ${profile.buildTools.join(', ') || '(none detected)'}`);
  sections.push(`- **Test Frameworks**: ${profile.testFrameworks.join(', ') || '(none detected)'}`);
  sections.push(`- **CI**: ${profile.ci ?? '(none detected)'}`);
  sections.push(`- **Package Manager**: ${profile.packageManager ?? '(none detected)'}`);
  sections.push('');

  // Directory Structure
  if (profile.directoryStructure && profile.directoryStructure.length > 0) {
    sections.push('## Directory Structure');
    sections.push('');
    sections.push('```');
    for (const dir of profile.directoryStructure) {
      sections.push(`${dir.name}/  (${dir.role})`);
      if (dir.children) {
        for (const child of dir.children) {
          sections.push(`  ${child.name}/`);
        }
      }
    }
    sections.push('```');
    sections.push('');
  }

  // Existing Documentation
  if (profile.existingDocs && profile.existingDocs.length > 0) {
    sections.push('## Existing Documentation');
    sections.push('');
    for (const doc of profile.existingDocs) {
      sections.push(`- \`${doc.path}\` (${doc.type})`);
    }
    sections.push('');
  }

  // Entry Points
  if (profile.entryPoints.length > 0) {
    sections.push('## Entry Points');
    sections.push('');
    for (const ep of profile.entryPoints) {
      sections.push(`- \`${ep}\``);
    }
    sections.push('');
  }

  // Architecture
  if (profile.architecturePattern !== 'single-package') {
    sections.push('## Architecture');
    sections.push('');
    sections.push(`Pattern: **${profile.architecturePattern}**`);
    if (profile.projectContext?.hasMonorepo) {
      sections.push('');
      sections.push('This project uses a monorepo structure.');
    }
    sections.push('');
  }

  return sections.join('\n');
};
