/**
 * Sprint 58: Prototype HTML 템플릿 — 5 Starting Point별 섹션 렌더링 (F181)
 */

import { type StartingPointType } from "../../discovery/types.js";
import { getBaseCSS, getTheme, type DesignTokenOverride } from "./prototype-styles.js";

export interface PrototypeData {
  title: string;
  tagline: string;
  problemStatement: string;
  solutionOverview: string;
  features: Array<{ title: string; description: string }>;
  marketStats: Array<{ label: string; value: string }>;
  competitors: string[];
  evaluationSummary: string;
  personaQuotes: Array<{ persona: string; quote: string }>;
  verdict: string;
  avgScore: number;
  ctaText: string;
}

// ─── 섹션 순서 정의 (Starting Point별) ───

export const SECTION_ORDER: Record<StartingPointType, string[]> = {
  idea:    ["hero", "solution", "problem", "market", "proof", "cta"],
  market:  ["hero", "market", "problem", "solution", "proof", "cta"],
  problem: ["hero", "problem", "solution", "market", "proof", "cta"],
  tech:    ["hero", "solution", "market", "problem", "proof", "cta"],
  service: ["hero", "problem", "solution", "proof", "market", "cta"],
};

// ─── 섹션 렌더러 ───

function renderHero(data: PrototypeData, theme: ReturnType<typeof getTheme>): string {
  return `<div class="hero"><h1>${escapeHtml(data.title)}</h1><p>${escapeHtml(data.tagline)}</p><a class="cta" href="#">${escapeHtml(data.ctaText)}</a></div>`;
}

function renderProblem(data: PrototypeData): string {
  return `<div class="section"><h2>해결하려는 문제</h2><p>${escapeHtml(data.problemStatement)}</p></div>`;
}

function renderSolution(data: PrototypeData, theme: ReturnType<typeof getTheme>): string {
  const featureCards = data.features.slice(0, 3).map(f =>
    `<div class="card"><h3>${escapeHtml(f.title)}</h3><p>${escapeHtml(f.description)}</p></div>`
  ).join("");
  return `<div class="section"><h2>솔루션</h2><p>${escapeHtml(data.solutionOverview)}</p><div class="cards">${featureCards}</div></div>`;
}

function renderMarket(data: PrototypeData): string {
  const stats = data.marketStats.slice(0, 3).map(s =>
    `<div class="stat"><div class="value">${escapeHtml(s.value)}</div><div class="label">${escapeHtml(s.label)}</div></div>`
  ).join("");
  return `<div class="section"><h2>시장 기회</h2><div class="cards">${stats}</div></div>`;
}

function renderProof(data: PrototypeData): string {
  const quotes = data.personaQuotes.slice(0, 3).map(q =>
    `<div class="quote"><strong>${escapeHtml(q.persona)}</strong><p>"${escapeHtml(q.quote)}"</p></div>`
  ).join("");
  const scoreBar = `<div class="stat"><div class="value">${data.avgScore.toFixed(1)}/10</div><div class="label">전문가 평균 평가</div></div>`;
  return `<div class="section"><h2>검증 결과</h2>${scoreBar}${quotes}</div>`;
}

function renderCta(data: PrototypeData, theme: ReturnType<typeof getTheme>): string {
  return `<div class="cta-section"><h2>다음 단계</h2><p>${escapeHtml(data.evaluationSummary)}</p><a class="btn" href="#">자세히 보기</a></div>`;
}

// ─── HTML 조립 ───

export function renderPrototypeHtml(
  data: PrototypeData,
  startingPoint: StartingPointType,
  tokens?: DesignTokenOverride,
): string {
  const theme = getTheme(data.verdict);
  const css = getBaseCSS(theme, tokens);
  const order = SECTION_ORDER[startingPoint] ?? SECTION_ORDER.idea;

  const renderers: Record<string, () => string> = {
    hero: () => renderHero(data, theme),
    problem: () => renderProblem(data),
    solution: () => renderSolution(data, theme),
    market: () => renderMarket(data),
    proof: () => renderProof(data),
    cta: () => renderCta(data, theme),
  };

  const body = order.map(sec => renderers[sec]?.() ?? "").join("\n");

  return `<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(data.title)} — Prototype</title>
  <style>${css}</style>
</head>
<body>
${body}
<footer style="text-align:center;padding:20px;color:#9ca3af;font-size:0.75rem;">
  Generated by Foundry-X Discovery Pipeline — ${new Date().toISOString().split("T")[0]}
</footer>
</body>
</html>`;
}

export function escapeHtml(str: string): string {
  return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
