import { defineConfig } from "tinacms";

export default defineConfig({
  branch: process.env.TINA_BRANCH ?? "master",
  clientId: process.env.VITE_TINA_CLIENT_ID ?? "",
  token: process.env.TINA_TOKEN ?? "",
  build: {
    outputFolder: "admin",
    publicFolder: "public",
  },
  schema: {
    collections: [
      {
        name: "landing",
        label: "Landing Pages",
        path: "content/landing",
        format: "md",
        fields: [
          {
            type: "string",
            name: "title",
            label: "Title",
            isTitle: true,
            required: true,
          },
          { type: "string", name: "section", label: "Section" },
          { type: "string", name: "tagline", label: "Tagline" },
          { type: "string", name: "phase", label: "Current Phase" },
          { type: "string", name: "phaseTitle", label: "Phase Title" },
          {
            type: "object",
            name: "stats",
            label: "Stats",
            list: true,
            fields: [
              { type: "string", name: "value", label: "Value" },
              { type: "string", name: "label", label: "Label" },
            ],
          },
          { type: "number", name: "sort_order", label: "Sort Order" },
          {
            type: "rich-text",
            name: "body",
            label: "Body",
            isBody: true,
          },
        ],
      },
      {
        name: "navigation",
        label: "Navigation",
        path: "content/navigation",
        format: "json",
        fields: [
          {
            type: "string",
            name: "navId",
            label: "Navigation ID",
            isTitle: true,
            required: true,
          },
          {
            type: "object",
            name: "topItems",
            label: "Top Items",
            list: true,
            fields: [
              { type: "string", name: "href", label: "Path", required: true },
              { type: "string", name: "label", label: "Label", required: true },
              {
                type: "string",
                name: "iconKey",
                label: "Icon Key",
                required: true,
              },
              { type: "boolean", name: "visible", label: "Visible" },
              { type: "number", name: "sortOrder", label: "Sort Order" },
            ],
          },
          {
            type: "object",
            name: "processGroups",
            label: "Process Groups",
            list: true,
            fields: [
              { type: "string", name: "key", label: "Key", required: true },
              { type: "string", name: "label", label: "Label", required: true },
              { type: "string", name: "iconKey", label: "Icon Key" },
              {
                type: "string",
                name: "stageColor",
                label: "Stage Color (CSS class)",
              },
              { type: "number", name: "sortOrder", label: "Sort Order" },
              { type: "boolean", name: "visible", label: "Visible" },
              {
                type: "boolean",
                name: "collapsed",
                label: "Default Collapsed",
              },
              {
                type: "string",
                name: "badge",
                label: "Badge Text",
              },
              {
                type: "object",
                name: "items",
                label: "Items",
                list: true,
                fields: [
                  {
                    type: "string",
                    name: "href",
                    label: "Path",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "label",
                    label: "Label",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "iconKey",
                    label: "Icon Key",
                    required: true,
                  },
                  { type: "boolean", name: "visible", label: "Visible" },
                  { type: "number", name: "sortOrder", label: "Sort Order" },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "bottomItems",
            label: "Bottom Items",
            list: true,
            fields: [
              { type: "string", name: "href", label: "Path", required: true },
              { type: "string", name: "label", label: "Label", required: true },
              {
                type: "string",
                name: "iconKey",
                label: "Icon Key",
                required: true,
              },
              { type: "boolean", name: "visible", label: "Visible" },
              { type: "number", name: "sortOrder", label: "Sort Order" },
            ],
          },
          {
            type: "object",
            name: "adminGroups",
            label: "Admin Groups",
            list: true,
            fields: [
              { type: "string", name: "key", label: "Key", required: true },
              { type: "string", name: "label", label: "Label", required: true },
              { type: "string", name: "iconKey", label: "Icon Key" },
              { type: "number", name: "sortOrder", label: "Sort Order" },
              { type: "boolean", name: "visible", label: "Visible" },
              {
                type: "object",
                name: "items",
                label: "Items",
                list: true,
                fields: [
                  { type: "string", name: "href", label: "Path", required: true },
                  { type: "string", name: "label", label: "Label", required: true },
                  { type: "string", name: "iconKey", label: "Icon Key", required: true },
                  { type: "boolean", name: "visible", label: "Visible" },
                  { type: "number", name: "sortOrder", label: "Sort Order" },
                ],
              },
            ],
          },
        ],
      },
      {
        name: "wiki",
        label: "Wiki Pages",
        path: "content/wiki",
        format: "md",
        fields: [
          {
            type: "string",
            name: "title",
            label: "Title",
            isTitle: true,
            required: true,
          },
          { type: "string", name: "category", label: "Category" },
          {
            type: "rich-text",
            name: "body",
            label: "Body",
            isBody: true,
          },
        ],
      },
    ],
  },
});
